const data={
    products:[
        {
            _id:'1',
            name:'Gaming Keyboard',
            category:'keyboard',
            image:'/images/p1.jpg',
            price:120,
            countInStock:10,
            brand:'logitech',
            rating:1,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Mouse',
            category:'mouse',
            image:'/images/p2.jpg',
            price:40,
            countInStock:15,
            brand:'logitech',
            rating:3,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Screen',
            category:'screens',
            image:'/images/p3.jpg',
            price:400,
            countInStock:3,
            brand:'samsung',
            rating:3.8,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Portable Computer',
            category:'computer',
            image:'/images/p4.jpg',
            price:800,
            countInStock:5,
            brand:'logitech',
            rating:4.8,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Vertical Mouse',
            category:'mouse',
            image:'/images/p5.jpg',
            price:120,
            countInStock:9,
            brand:'logitech',
            rating:5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Headphones',
            category:'keyboard',
            image:'/images/p6.jpg',
            price:120,
            countInStock:0,
            brand:'logitech',
            rating:3.7,
            numReviews:10,
            description:'high quality product',
        }
    ]
}

export default data;